version: '3'
services:
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: medinsighthub
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/medinsighthub
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: postgres
