feign:
  client:
    config:
      default:
        connectTimeout : 5000
        readTimeout : 5000
        loggerLevel : basic
servlet:
  multipart:
    max-request-size: 10MB
    max-file-size: 10MB